[build-system]
requires = ['setuptools>=40.8.0', 'wheel']
build-backend = 'setuptools.build_meta:__legacy__'

[tool.black]
line-length = 120
target-version = ['py37']
include = '\.pyi?$'
exclude = 'migrations'

[tool.isort]
profile = "black"
multi_line_output = 3
skip = 'migrations'
